---
title: "Diamond sizes"
date: 2016-08-25
output: html_document

---

```{r setup, include = FALSE}
library(ggplot2)
library(dplyr)

knitr::opts_chunk$set(echo=FALSE)

smaller <- diamonds %>% 
  filter(carat <= 2.5)
```

We have data about `r nrow(diamonds)` diamonds. Only 
`r nrow(diamonds) - nrow(smaller)` are larger than
2.5 carats. The distribution of the remainder is shown
below:

```{r}
smaller %>% 
  ggplot(aes(carat)) + 
  geom_freqpoly(binwidth = 0.01)
```

---
27.3.1 Exercise 3
---
---
The majority of diamonds sampled are smaller than 1.5 carat. As size increases, the count of diamonds decreases.
---

---
27.4.7 Exercise 1
---
---
How diamond sizes vary by cut, colour, and clarity. 
---

```{r}
smaller %>% 
  ggplot(aes(x=carat, color=cut)) + 
    geom_freqpoly(binwidth = 0.01) +
    facet_wrap(~cut) +
    labs(x="Carat",y="Count",title="How Diamond Sizes Vary by Cut")

smaller %>%
  ggplot(aes(x=carat, y=cut, color=cut, fill=cut)) +
    geom_violin() +
    labs(x="Carat",y="Cut",title="Comparing Distribution of Diamond Size by Cut")

```

```{r}
smaller %>% 
  ggplot(aes(x=carat, color=color)) + 
    geom_freqpoly(binwidth = 0.01) +
    facet_wrap(~color) +
    labs(x="Carat",y="Count",title="How Diamond Sizes Vary by Color")

smaller %>%
  ggplot(aes(x=carat, y=color, color=color, fill=color)) +
    geom_violin() +
    labs(x="Carat",y="Color",title="Comparing Distribution of Diamond Size by Color")
```

```{r}
smaller %>% 
  ggplot(aes(x=carat, color=clarity)) + 
    geom_freqpoly(binwidth = 0.01) +
    facet_wrap(~clarity) +
    labs(x="Carat",y="Count",title="How Diamond Sizes Vary by Clarity")

smaller %>%
  ggplot(aes(x=carat, y=clarity, color=clarity, fill=clarity)) +
    geom_violin() +
    labs(x="Carat",y="Clarity",title="Comparing Distribution of Diamond Size by Clarity")
```